# Generated by Django 4.2 on 2025-05-26 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crianca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_de_nascimento', models.DateField()),
                ('sal', models.CharField(choices=[('selecione', 'Selecione'), ('sala 1', 'Sala 1'), ('sala 2', 'Sala 2')], default='selecione', max_length=100, verbose_name='Qual sala?')),
                ('ru', models.CharField(max_length=200)),
                ('num', models.IntegerField(verbose_name='Num')),
                ('cid', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=200)),
                ('mor_q', models.CharField(choices=[('selecione', 'Selecione'), ('avós', 'Avós'), ('Pais', 'Pais'), ('Outros', 'Outros')], default='selecione', max_length=200, verbose_name='Mora com quem?')),
                ('irm', models.CharField(choices=[('selecione', 'Selecione'), ('sim', 'Sim'), ('não', 'Não')], default='selecione', max_length=9, verbose_name='Tem irmãos?')),
                ('pr_sau', models.CharField(choices=[('selecione', 'Selecione'), ('sim', 'Sim'), ('não', 'Não')], default='selecione', max_length=200, verbose_name='Prob. saúde')),
                ('med', models.CharField(choices=[('selecione', 'Selecione'), ('sim', 'Sim'), ('não', 'Não')], default='selecione', max_length=200, verbose_name='Medic. contínuo?')),
                ('med_q', models.CharField(max_length=50, verbose_name='Medic qual?')),
                ('aler', models.CharField(choices=[('selecione', 'Selecione'), ('sim', 'Sim'), ('não', 'Não')], default='selecione', max_length=200, verbose_name='Tem alergias?')),
                ('aler_q', models.CharField(max_length=200, verbose_name='Alergias qual?')),
            ],
            options={
                'verbose_name': 'Criança',
                'verbose_name_plural': 'Crianças',
            },
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('profissao', models.CharField(max_length=200, verbose_name='Profissão')),
            ],
            options={
                'verbose_name': 'Cuidador',
                'verbose_name_plural': 'Cuidadores',
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('profissao', models.CharField(max_length=200, verbose_name='Profissão')),
                ('local_trabalho', models.CharField(blank=True, max_length=100, null=True)),
                ('auth_user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis_painel', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
            },
        ),
        migrations.CreateModel(
            name='Registro_Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('cafe', models.CharField(choices=[('selecione', 'Selecione'), ('nada', 'Nada'), ('pouco', 'Pouco'), ('tudo', 'Tudo')], default='selecione', max_length=100, verbose_name='Café')),
                ('alm', models.CharField(choices=[('selecione', 'Selecione'), ('nada', 'Nada'), ('pouco', 'Pouco'), ('tudo', 'Tudo')], default='selecione', max_length=100, verbose_name='Almoço')),
                ('col', models.CharField(choices=[('selecione', 'Selecione'), ('nada', 'Nada'), ('pouco', 'Pouco'), ('tudo', 'Tudo')], default='selecione', max_length=100, verbose_name='Colação')),
                ('jnt', models.CharField(choices=[('selecione', 'Selecione'), ('nada', 'Nada'), ('pouco', 'Pouco'), ('tudo', 'Tudo')], default='selecione', max_length=100, verbose_name='Janta')),
                ('ev_L', models.CharField(choices=[('selecione', 'Selecione'), ('1', '1'), ('2', '2'), ('3', '3')], default='selecione', max_length=9, verbose_name='Ev. Líquida')),
                ('ev_P', models.CharField(choices=[('selecione', 'Selecione'), ('1', '1'), ('2', '2'), ('3', '3')], default='selecione', max_length=9, verbose_name='Ev. Pastosa')),
                ('bnh', models.CharField(choices=[('selecione', 'Selecione'), ('sim', 'Sim'), ('não', 'Não')], default='selecione', max_length=100, verbose_name='Banho')),
                ('sono', models.CharField(choices=[('selecione', 'Selecione'), ('tranquilo', 'Tranquilo'), ('agitado', 'Agitado'), ('não dormiu', 'Não dormiu')], default='selecione', max_length=100)),
                ('obs', models.TextField(max_length=25, verbose_name='Observações')),
                ('crianca', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='painel.crianca', verbose_name='Criança')),
                ('cuidador', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='painel.cuidador')),
            ],
            options={
                'verbose_name': 'Registro Diário',
                'verbose_name_plural': 'Registro Diário',
            },
        ),
        migrations.AddField(
            model_name='crianca',
            name='resp',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='criancas', to='painel.responsavel', verbose_name='Responsável'),
        ),
    ]
