# Generated by Django 5.2 on 2025-05-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crianca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('mora_com_quem', models.CharField(max_length=200)),
                ('tem_irmaos', models.CharField(max_length=200)),
                ('problema_saude_qual', models.CharField(max_length=200)),
                ('medicamento_continuo', models.CharField(max_length=200)),
                ('mendicamento_qual', models.CharField(max_length=200)),
                ('tem_alergias', models.CharField(max_length=200)),
                ('alergias_qual', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('profissao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Registro_diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crianca_id', models.CharField(max_length=100)),
                ('cuidador_id', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('cafe_da_manha', models.CharField(max_length=100)),
                ('almoco', models.CharField(blank=True, max_length=100, null=True)),
                ('colacao', models.CharField(max_length=100)),
                ('jantar', models.CharField(max_length=100)),
                ('evacuacao_liquida', models.CharField(max_length=100)),
                ('evacuacao_pastosa', models.CharField(max_length=100)),
                ('banho', models.CharField(max_length=100)),
                ('sono', models.CharField(max_length=100)),
                ('observacoes', models.CharField(max_length=100)),
                ('assinatura', models.CharField(default='não assinado', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('profissao', models.CharField(max_length=200)),
                ('local_trabalho', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
