# Generated by Django 5.2 on 2025-05-05 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crianca',
            new_name='Crianças',
        ),
    ]
