# Generated by Django 5.2 on 2025-05-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_crianca_crianças'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crianças',
            new_name='Crianca',
        ),
    ]
