# Generated by Django 5.2 on 2025-05-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_crianças_crianca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('cidade', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=200)),
            ],
        ),
    ]
