# Generated by Django 5.2 on 2025-05-06 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_endereco'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Endereco',
        ),
        migrations.RenameField(
            model_name='crianca',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='cuidador',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='responsavel',
            old_name='name',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='registro_diario',
            name='crianca_id',
        ),
        migrations.RemoveField(
            model_name='registro_diario',
            name='cuidador_id',
        ),
        migrations.AddField(
            model_name='crianca',
            name='responsavel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='criancas', to='home.responsavel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro_diario',
            name='crianca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='home.crianca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro_diario',
            name='cuidador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='home.cuidador'),
        ),
    ]
