# Generated by Django 5.2 on 2025-05-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_endereco_rename_name_crianca_nome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crianca',
            old_name='idade',
            new_name='data_de_nascimento',
        ),
        migrations.AddField(
            model_name='crianca',
            name='cep',
            field=models.CharField(default='00000-000', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crianca',
            name='cidade',
            field=models.CharField(default='são josè dos campos', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crianca',
            name='endereco',
            field=models.CharField(default='321', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crianca',
            name='numero',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crianca',
            name='rua',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
