# Generated by Django 5.2 on 2025-05-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_idade_crianca_data_de_nascimento_crianca_cep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crianca',
            name='endereco',
        ),
    ]
