# Generated by Django 5.2 on 2025-05-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_crianca_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crianca',
            name='data_de_nascimento',
            field=models.DateField(),
        ),
    ]
