# Generated by Django 5.2 on 2025-05-13 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_crianca_data_de_nascimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crianca',
            options={'verbose_name': 'Criança', 'verbose_name_plural': 'Crianças'},
        ),
        migrations.AlterModelOptions(
            name='cuidador',
            options={'verbose_name': 'Cuidador', 'verbose_name_plural': 'Cuidadores'},
        ),
        migrations.AlterModelOptions(
            name='registro_diario',
            options={'verbose_name': 'Registro Diário', 'verbose_name_plural': 'Registro Diário'},
        ),
        migrations.AlterModelOptions(
            name='responsavel',
            options={'verbose_name': 'Responsável', 'verbose_name_plural': 'Responsáveis'},
        ),
        migrations.AlterField(
            model_name='crianca',
            name='alergias_qual',
            field=models.CharField(max_length=200, verbose_name='Alergias qual?'),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='medicamento_continuo',
            field=models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], max_length=200, verbose_name='Medicamento continuo?'),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='mendicamento_qual',
            field=models.CharField(max_length=200, verbose_name='Medicamento qual?'),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='mora_com_quem',
            field=models.CharField(choices=[('avós', 'avós'), ('Pais', 'Pais'), ('Outros', 'Outros')], max_length=200, verbose_name='Mora com quem?'),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='numero',
            field=models.IntegerField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='problema_saude_qual',
            field=models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], max_length=200, verbose_name='problema saúde qual'),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criancas', to='home.responsavel', verbose_name='responsável'),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='tem_alergias',
            field=models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], max_length=200, verbose_name='Tém alergias?'),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='tem_irmaos',
            field=models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], max_length=3, verbose_name='Tem irmãos?'),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='profissao',
            field=models.CharField(max_length=200, verbose_name='Profissão'),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='almoco',
            field=models.CharField(blank=True, choices=[('nada', 'nada'), ('pouco', 'pouco'), ('tudo', 'tudo')], max_length=100, null=True, verbose_name='Almoço'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='assinatura',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='banho',
            field=models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], max_length=100),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='cafe_da_manha',
            field=models.CharField(choices=[('nada', 'nada'), ('pouco', 'pouco'), ('tudo', 'tudo')], max_length=100, verbose_name='Café da manhã'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='colacao',
            field=models.CharField(choices=[('nada', 'nada'), ('pouco', 'pouco'), ('tudo', 'tudo')], max_length=100, verbose_name='Colação'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='crianca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='home.crianca', verbose_name='Criança'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='evacuacao_liquida',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=100, verbose_name='Evacuação liquida'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='evacuacao_pastosa',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=100, verbose_name='Evacuação pastosa'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='jantar',
            field=models.CharField(choices=[('nada', 'nada'), ('pouco', 'pouco'), ('tudo', 'tudo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='observacoes',
            field=models.TextField(max_length=100, verbose_name='observações'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='sono',
            field=models.CharField(choices=[('tranquilo', 'tranquilo'), ('agitado', 'agitado'), ('não dormiu', 'não dormiu')], max_length=100),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='profissao',
            field=models.CharField(max_length=200, verbose_name='Profissão'),
        ),
    ]
