# Generated by Django 5.2 on 2025-05-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_crianca_options_alter_cuidador_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crianca',
            name='qual_sala',
            field=models.CharField(choices=[('sala 1', 'sala 1'), ('sala 2', 'sala 2')], default=1, max_length=100, verbose_name='Qual e a sala?'),
            preserve_default=False,
        ),
    ]
