# Generated by Django 5.2 on 2025-05-15 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_crianca_qual_sala'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_diario',
            name='assinatura',
        ),
    ]
