# Generated by Django 5.2 on 2025-05-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_registro_diario_assinatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_diario',
            name='cafe_da_manha',
        ),
        migrations.AddField(
            model_name='registro_diario',
            name='cafe',
            field=models.CharField(choices=[('nada', 'nada'), ('pouco', 'pouco'), ('tudo', 'tudo')], default=1, max_length=100, verbose_name='Café'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='evacuacao_liquida',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=100, verbose_name='Ev.Liquida'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='evacuacao_pastosa',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=100, verbose_name='Ev.Pastosa'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='observacoes',
            field=models.TextField(max_length=10, verbose_name='observações'),
        ),
    ]
