# Generated by Django 5.2 on 2025-05-16 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_registro_diario_cafe_da_manha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_diario',
            old_name='evacuacao_liquida',
            new_name='ev_Liquida',
        ),
        migrations.RenameField(
            model_name='registro_diario',
            old_name='evacuacao_pastosa',
            new_name='ev_Pastosa',
        ),
    ]
