# Generated by Django 5.2 on 2025-05-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_evacuacao_liquida_registro_diario_ev_liquida_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_diario',
            old_name='observacoes',
            new_name='obs',
        ),
    ]
