# Generated by Django 5.2 on 2025-05-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_observacoes_registro_diario_obs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_diario',
            old_name='ev_Liquida',
            new_name='ev_L',
        ),
        migrations.RenameField(
            model_name='registro_diario',
            old_name='ev_Pastosa',
            new_name='ev_P',
        ),
    ]
