# Generated by Django 5.2 on 2025-05-16 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_ev_liquida_registro_diario_ev_l_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_diario',
            old_name='banho',
            new_name='bnh',
        ),
    ]
