# Generated by Django 5.2 on 2025-05-16 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_banho_registro_diario_bnh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_diario',
            old_name='colacao',
            new_name='col',
        ),
    ]
