# Generated by Django 5.2 on 2025-05-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_colacao_registro_diario_col'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_diario',
            old_name='almoco',
            new_name='alm',
        ),
        migrations.RenameField(
            model_name='registro_diario',
            old_name='jantar',
            new_name='jnt',
        ),
    ]
