# Generated by Django 5.2 on 2025-05-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_almoco_registro_diario_alm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_diario',
            old_name='alm',
            new_name='almoco',
        ),
    ]
