# Generated by Django 5.2 on 2025-05-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rename_alm_registro_diario_almoco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_diario',
            old_name='almoco',
            new_name='alm',
        ),
    ]
