# Generated by Django 5.2 on 2025-05-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_almoco_registro_diario_alm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crianca',
            name='qual_sala',
            field=models.CharField(choices=[('sala 1', 'sala 1'), ('sala 2', 'sala 2')], max_length=100, verbose_name='qual_sala?'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='bnh',
            field=models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], max_length=100, verbose_name='Banho'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='jnt',
            field=models.CharField(choices=[('nada', 'nada'), ('pouco', 'pouco'), ('tudo', 'tudo')], max_length=100, verbose_name='Janta'),
        ),
    ]
