# Generated by Django 5.2 on 2025-05-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_crianca_qual_sala_alter_registro_diario_bnh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crianca',
            name='problema_saude_qual',
        ),
        migrations.AddField(
            model_name='crianca',
            name='problema_saude',
            field=models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], default=1, max_length=200, verbose_name='problema saúde'),
            preserve_default=False,
        ),
    ]
