# Generated by Django 5.2 on 2025-05-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_crianca_problema_saude_qual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crianca',
            name='alergias_qual',
            field=models.CharField(max_length=200, verbose_name='alergias_qual?'),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='tem_alergias',
            field=models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], max_length=200, verbose_name='alergias?'),
        ),
    ]
