# Generated by Django 5.2 on 2025-05-16 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_crianca_alergias_qual_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crianca',
            old_name='medicamento_continuo',
            new_name='medic_continuo',
        ),
    ]
