# Generated by Django 5.2 on 2025-05-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_rename_medicamento_continuo_crianca_medic_continuo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crianca',
            name='mendicamento_qual',
        ),
        migrations.AddField(
            model_name='crianca',
            name='mendic_qual',
            field=models.CharField(default=1, max_length=200, verbose_name='Medic qual?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crianca',
            name='medic_continuo',
            field=models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], max_length=200, verbose_name='Medic continuo?'),
        ),
    ]
