# Generated by Django 5.2 on 2025-05-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_crianca_mendicamento_qual_crianca_mendic_qual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crianca',
            name='problema_saude',
        ),
        migrations.AddField(
            model_name='crianca',
            name='prob_saude',
            field=models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], default=1, max_length=200, verbose_name='prob saúde'),
            preserve_default=False,
        ),
    ]
