# Generated by Django 5.2 on 2025-05-16 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_crianca_problema_saude_crianca_prob_saude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crianca',
            old_name='mendic_qual',
            new_name='medic_qual',
        ),
    ]
