# Generated by Django 5.2 on 2025-05-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_rename_mendic_qual_crianca_medic_qual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crianca',
            name='alergias_qual',
        ),
        migrations.RemoveField(
            model_name='crianca',
            name='numero',
        ),
        migrations.AddField(
            model_name='crianca',
            name='aler_qual',
            field=models.CharField(default=1, max_length=200, verbose_name='aler_qual?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crianca',
            name='num',
            field=models.IntegerField(default=1, verbose_name='Num'),
            preserve_default=False,
        ),
    ]
