# Generated by Django 5.2 on 2025-05-19 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_remove_crianca_alergias_qual_remove_crianca_numero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='auth_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='auth user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crianca',
            name='tem_alergias',
            field=models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], max_length=200, verbose_name='tem_alergias?'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='ev_L',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1, verbose_name='Ev.Liquida'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='ev_P',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1, verbose_name='Ev.Pastosa'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='obs',
            field=models.TextField(max_length=25, verbose_name='observações'),
        ),
    ]
