# Generated by Django 5.2 on 2025-05-20 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_responsavel_auth_user_alter_crianca_tem_alergias_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='crianca',
            old_name='qual_sala',
            new_name='sal',
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='auth_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
