# Generated by Django 5.2 on 2025-05-20 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_rename_qual_sala_crianca_sal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crianca',
            old_name='rua',
            new_name='ru',
        ),
    ]
