# Generated by Django 5.2 on 2025-05-20 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_rename_rua_crianca_ru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crianca',
            old_name='cidade',
            new_name='cid',
        ),
    ]
