# Generated by Django 5.2 on 2025-05-20 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_rename_cidade_crianca_cid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crianca',
            old_name='mora_com_quem',
            new_name='mor_q',
        ),
    ]
