# Generated by Django 5.2 on 2025-05-20 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_rename_mora_com_quem_crianca_mor_q'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crianca',
            old_name='tem_irmaos',
            new_name='irm',
        ),
    ]
