# Generated by Django 5.2 on 2025-05-20 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_rename_tem_irmaos_crianca_irm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crianca',
            old_name='prob_saude',
            new_name='pr_sau',
        ),
    ]
