# Generated by Django 5.2 on 2025-05-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_rename_prob_saude_crianca_pr_sau'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crianca',
            old_name='medic_continuo',
            new_name='med',
        ),
    ]
