# Generated by Django 5.2 on 2025-05-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_rename_medic_continuo_crianca_med'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crianca',
            old_name='medic_qual',
            new_name='med_q',
        ),
    ]
