# Generated by Django 5.2 on 2025-05-20 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_rename_medic_qual_crianca_med_q'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crianca',
            old_name='tem_alergias',
            new_name='aler',
        ),
    ]
