# Generated by Django 5.2 on 2025-05-20 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_rename_tem_alergias_crianca_aler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crianca',
            old_name='aler_qual',
            new_name='aler_q',
        ),
    ]
