# Generated by Django 5.2 on 2025-05-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_rename_aler_qual_crianca_aler_q'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crianca',
            old_name='responsavel',
            new_name='resp',
        ),
    ]
