# Generated by Django 5.2 on 2025-05-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_rename_responsavel_crianca_resp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crianca',
            old_name='nome',
            new_name='nom',
        ),
    ]
