# Generated by Django 5.2 on 2025-05-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_rename_nome_crianca_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crianca',
            old_name='nom',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='crianca',
            name='med_q',
            field=models.CharField(max_length=50, verbose_name='Medic qual?'),
        ),
    ]
