# Generated by Django 4.2 on 2025-05-21 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0042_rename_nom_crianca_nome_alter_crianca_med_q'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crianca',
            name='aler',
            field=models.CharField(choices=[('selecione', 'Selecione'), ('sim', 'Sim'), ('não', 'Não')], default='não', max_length=200, verbose_name='Tem alergias?'),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='aler_q',
            field=models.CharField(max_length=200, verbose_name='Alergias qual?'),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='irm',
            field=models.CharField(choices=[('selecione', 'Selecione'), ('sim', 'Sim'), ('não', 'Não')], default='não', max_length=9, verbose_name='Tem irmãos?'),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='med',
            field=models.CharField(choices=[('selecione', 'Selecione'), ('sim', 'Sim'), ('não', 'Não')], default='não', max_length=200, verbose_name='Medic. contínuo?'),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='mor_q',
            field=models.CharField(choices=[('avós', 'Avós'), ('Pais', 'Pais'), ('Outros', 'Outros')], default='Pais', max_length=200, verbose_name='Mora com quem?'),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='pr_sau',
            field=models.CharField(choices=[('selecione', 'Selecione'), ('sim', 'Sim'), ('não', 'Não')], default='não', max_length=200, verbose_name='Prob. saúde'),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='resp',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='criancas', to='home.responsavel', verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='sal',
            field=models.CharField(choices=[('sala 1', 'Sala 1'), ('sala 2', 'Sala 2')], default='sala 1', max_length=100, verbose_name='Qual sala?'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='alm',
            field=models.CharField(choices=[('nada', 'Nada'), ('pouco', 'Pouco'), ('tudo', 'Tudo')], default='tudo', max_length=100, verbose_name='Almoço'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='bnh',
            field=models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], default='não', max_length=100, verbose_name='Banho'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='cafe',
            field=models.CharField(choices=[('nada', 'Nada'), ('pouco', 'Pouco'), ('tudo', 'Tudo')], default='tudo', max_length=100, verbose_name='Café'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='col',
            field=models.CharField(choices=[('nada', 'Nada'), ('pouco', 'Pouco'), ('tudo', 'Tudo')], default='tudo', max_length=100, verbose_name='Colação'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='crianca',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='home.crianca', verbose_name='Criança'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='cuidador',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='home.cuidador'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='ev_L',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=1, verbose_name='Ev. Líquida'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='ev_P',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=1, verbose_name='Ev. Pastosa'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='jnt',
            field=models.CharField(choices=[('nada', 'Nada'), ('pouco', 'Pouco'), ('tudo', 'Tudo')], default='tudo', max_length=100, verbose_name='Janta'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='obs',
            field=models.TextField(max_length=25, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='sono',
            field=models.CharField(choices=[('tranquilo', 'Tranquilo'), ('agitado', 'Agitado'), ('não dormiu', 'Não dormiu')], default='tranquilo', max_length=100),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='auth_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
