# Generated by Django 4.2 on 2025-05-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_crianca_aler_alter_crianca_aler_q_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crianca',
            name='aler',
            field=models.CharField(choices=[('selecione', 'Selecione'), ('sim', 'Sim'), ('não', 'Não')], default='selecione', max_length=200, verbose_name='Tem alergias?'),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='irm',
            field=models.CharField(choices=[('selecione', 'Selecione'), ('sim', 'Sim'), ('não', 'Não')], default='selecione', max_length=9, verbose_name='Tem irmãos?'),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='med',
            field=models.CharField(choices=[('selecione', 'Selecione'), ('sim', 'Sim'), ('não', 'Não')], default='selecione', max_length=200, verbose_name='Medic. contínuo?'),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='mor_q',
            field=models.CharField(choices=[('selecione', 'Selecione'), ('avós', 'Avós'), ('Pais', 'Pais'), ('Outros', 'Outros')], default='selecione', max_length=200, verbose_name='Mora com quem?'),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='pr_sau',
            field=models.CharField(choices=[('selecione', 'Selecione'), ('sim', 'Sim'), ('não', 'Não')], default='selecione', max_length=200, verbose_name='Prob. saúde'),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='sal',
            field=models.CharField(choices=[('selecione', 'Selecione'), ('sala 1', 'Sala 1'), ('sala 2', 'Sala 2')], default='selecione', max_length=100, verbose_name='Qual sala?'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='alm',
            field=models.CharField(choices=[('selecione', 'Selecione'), ('nada', 'Nada'), ('pouco', 'Pouco'), ('tudo', 'Tudo')], default='selecione', max_length=100, verbose_name='Almoço'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='bnh',
            field=models.CharField(choices=[('selecione', 'Selecione'), ('sim', 'Sim'), ('não', 'Não')], default='selecione', max_length=100, verbose_name='Banho'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='cafe',
            field=models.CharField(choices=[('selecione', 'Selecione'), ('nada', 'Nada'), ('pouco', 'Pouco'), ('tudo', 'Tudo')], default='selecione', max_length=100, verbose_name='Café'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='col',
            field=models.CharField(choices=[('selecione', 'Selecione'), ('nada', 'Nada'), ('pouco', 'Pouco'), ('tudo', 'Tudo')], default='selecione', max_length=100, verbose_name='Colação'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='ev_L',
            field=models.CharField(choices=[('selecione', 'Selecione'), ('1', '1'), ('2', '2'), ('3', '3')], default='selecione', max_length=9, verbose_name='Ev. Líquida'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='ev_P',
            field=models.CharField(choices=[('selecione', 'Selecione'), ('1', '1'), ('2', '2'), ('3', '3')], default='selecione', max_length=9, verbose_name='Ev. Pastosa'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='jnt',
            field=models.CharField(choices=[('selecione', 'Selecione'), ('nada', 'Nada'), ('pouco', 'Pouco'), ('tudo', 'Tudo')], default='selecione', max_length=100, verbose_name='Janta'),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='sono',
            field=models.CharField(choices=[('selecione', 'Selecione'), ('tranquilo', 'Tranquilo'), ('agitado', 'Agitado'), ('não dormiu', 'Não dormiu')], default='selecione', max_length=100),
        ),
    ]
