# Generated by Django 4.2 on 2025-05-26 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0044_alter_crianca_aler_alter_crianca_irm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='auth_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis_home', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
