# Generated by Django 5.2 on 2025-05-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('comunicação', 'comunicação'), ('evento', 'evento'), ('observação', 'observação'), ('pedagogicos', 'pedagogicos')], max_length=255, verbose_name='Tipo')),
                ('descricao', models.TextField(max_length=100, verbose_name='Descrições')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
            },
        ),
    ]
