# Generated by Django 5.2 on 2025-05-14 12:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='descricao',
            field=ckeditor.fields.RichTextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='tipo',
            field=models.CharField(choices=[('comunicacao', 'Comunicação'), ('evento', 'Evento'), ('observacao', 'Observação'), ('pedagogicos', 'Pedagógicos')], max_length=255, verbose_name='Tipo'),
        ),
    ]
