# Generated by Django 5.2 on 2025-05-14 12:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0002_alter_mensagem_descricao_alter_mensagem_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='descricao',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Descrição'),
        ),
    ]
