# Generated by Django 5.2 on 2025-05-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0003_alter_mensagem_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='images/user'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='tipo',
            field=models.CharField(choices=[('comunicacao', 'Comunicação'), ('evento', 'Evento'), ('observacao', 'Observação'), ('pedagogicos', 'Pedagógicos')], max_length=20, verbose_name='Tipo'),
        ),
    ]
