# Generated by Django 5.2 on 2025-05-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0004_mensagem_imagem_alter_mensagem_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='imagem',
            field=models.ImageField(default=1, upload_to='images/user'),
            preserve_default=False,
        ),
    ]
