# Generated by Django 5.2 on 2025-05-15 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_registro_diario_assinatura'),
        ('mensagem', '0005_alter_mensagem_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='crianca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mensagem', to='home.crianca', verbose_name='criança'),
            preserve_default=False,
        ),
    ]
