# Generated by Django 4.2 on 2025-05-21 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_crianca_aler_alter_crianca_aler_q_and_more'),
        ('mensagem', '0006_mensagem_crianca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='crianca',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='mensagem', to='home.crianca', verbose_name='Criança'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='tipo',
            field=models.CharField(choices=[('comunicacao', 'Comunicação'), ('evento', 'Evento'), ('observacao', 'Observação'), ('pedagogicos', 'Pedagógicos')], default='comunicacao', max_length=20, verbose_name='Tipo'),
        ),
    ]
