# Generated by Django 4.2 on 2025-05-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0007_alter_mensagem_crianca_alter_mensagem_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='tipo',
            field=models.CharField(choices=[('selecione', 'Selecione'), ('comunicacao', 'Comunicação'), ('evento', 'Evento'), ('observacao', 'Observação'), ('pedagogicos', 'Pedagógicos')], default='selecione', max_length=20, verbose_name='Tipo'),
        ),
    ]
